def build_trace(
    *,
    input_summary: dict,
    computed_signals: dict,
    strategy_name: str,
    triggered_rules: list[str],
    score_breakdown: dict,
    recommendation_ranking_trace: list[dict],
    confidence_notes: list[str],
    alignment_confidence: float,
    recommendation_confidence: list[dict],
    confidence_breakdown: dict,
    confidence_version: str,
    context_applied: bool = False,
    context_notes: list[str] | None = None,
    context_version: str = "ctx_v1",
    context_json: dict | None = None,
    engine_version: str,
) -> dict:
    context_notes = context_notes or []
    context_json = context_json or {}
    return {
        "input_summary": input_summary,
        "computed_signals": computed_signals,
        "goal_strategy_applied": strategy_name,
        "triggered_rules": triggered_rules,
        "score_breakdown": score_breakdown,
        "recommendation_ranking_trace": recommendation_ranking_trace,
        "confidence_notes": confidence_notes,
        "alignment_confidence": alignment_confidence,
        "recommendation_confidence": recommendation_confidence,
        "confidence_breakdown": confidence_breakdown,
        "confidence_version": confidence_version,
        "context_applied": context_applied,
        "context_notes": context_notes,
        "context_version": context_version,
        "context_json": context_json,
        "engine_version": engine_version,
    }
